services:
  streetcode.rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648

  streetcode.mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "4002:1433"
    environment:
      SA_PASSWORD: "DatabaseStrongPassword123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql

  streetcode.identity:
    image: ${DOCKER_REGISTRY-}streetcodeidentity
    build:
      context: .
      dockerfile: Streedcode.Identity/Dockerfile
    depends_on:
      - streetcode.mssql
      - streetcode.rabbitmq
    ports:
      - "5003:80"
      - "5004:443"

  streetcode.webapi:
    image: ${DOCKER_REGISTRY-}streetcodewebapi
    build:
      context: .
      dockerfile: Streetcode.WebApi/Dockerfile
    depends_on:
      - streetcode.mssql
      - streetcode.rabbitmq
    ports:
      - "5000:80"
      - "5001:443"

  streetcode.redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mssql-data:
  redis-data:

