name: Deploy Identity microservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Streetcode/Streetcode.Identity/Streetcode.Identity.csproj

      - name: Build
        run: dotnet build ./Streetcode/Streetcode.Identity/Streetcode.Identity.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./Streetcode/Streetcode.Identity/Streetcode.Identity.csproj -configuration Release -o ./publish/identity

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish/identity

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-identity-eu-prod-001'
          slot-name: 'production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_Identity }} #should be added to secrets
